{% set name = "itksn" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6445136cb539d0d2f7df744f1c6fbea5fb7b3a661d295a55a905c99c026c6889

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - itksn = itksn.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=0.7
    - hatch-vcs
  run:
    - python >=3.7
    - typing_extensions >=3.7   # python < 3.8
    - typer
    - construct >=2.10

test:
  imports:
    - itksn
  commands:
    - itksn --version

about:
  home: https://github.com/kratsg/itksn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: ITk Serial Number parser
  description: ITk Serial Number parser
  doc_url: https://kratsg.github.io/itksn/
  dev_url: https://github.com/kratsg/itksn

extra:
  recipe-maintainers:
    - kratsg
